import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { Mb1ProgramTreeGeneratedModule, Mb1ProgramTreeGeneratedSharedModule } from './generated/module.js';
import { Mb1ProgramTreeValidator, registerValidationChecks } from './mb-1-program-tree-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type Mb1ProgramTreeAddedServices = {
    validation: {
        Mb1ProgramTreeValidator: Mb1ProgramTreeValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type Mb1ProgramTreeServices = LangiumServices & Mb1ProgramTreeAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const Mb1ProgramTreeModule: Module<Mb1ProgramTreeServices, PartialLangiumServices & Mb1ProgramTreeAddedServices> = {
    validation: {
        Mb1ProgramTreeValidator: () => new Mb1ProgramTreeValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMb1ProgramTreeServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Mb1ProgramTree: Mb1ProgramTreeServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        Mb1ProgramTreeGeneratedSharedModule
    );
    const Mb1ProgramTree = inject(
        createDefaultModule({ shared }),
        Mb1ProgramTreeGeneratedModule,
        Mb1ProgramTreeModule
    );
    shared.ServiceRegistry.register(Mb1ProgramTree);
    registerValidationChecks(Mb1ProgramTree);
    return { shared, Mb1ProgramTree };
}
